### ISSUE TITLE
panic htmp/template

### ISSUE THREAD

**Issue by xseth** [ipstatic/unifi-captive-portal#3]
Hi, 
I have this error when I run unifi-captive portal
panic: html/template: pattern matches no files: `templates/*`

goroutine 1 [running]:
html/template.Must(0x0, 0x9f3480, 0xc42001efe0, 0x9f3480)
	/usr/local/go/src/html/template/template.go:372 +0x54

for compile and install I run go get unifi-captive-portal

**Comment by ipstatic** [comment]
Hi xseth,
What are you setting the template.dir flag to? By default it uses ./templates. Do you have the example templates populating that directory?

**Comment by xseth** [comment]
I move the folder unifi-captive-portal in my home/work/src/
And I compiled with go get unifi-captive-portal I don't know if it's the right process I'll start with go language. 
I have this in the folder: ls /usr/local/go/src/html/template/
attr.go               content_test.go       css_test.go           escape.go             example_test.go       js.go                 template_test.go      url.go
clone_test.go         context.go            doc.go                escape_test.go        html.go               js_test.go            transition.go         url_test.go
content.go            css.go                error.go              examplefiles_test.go  html_test.go          template.go           transition_test.go
Thank you for your reply

**Comment by ipstatic** [comment]
Hmm, you should have just the following in the templates folder:

```
error.html
form.html
landing.html
layout.html
thankyou.html
```
Is that the source of the Go Template function?

**Comment by ipstatic** [comment]
Where is the directory that you run unifi-captive-portal from? By default this program expects a ./templates directory inside of that with the included templates. Do you have that defined? Or are you passing the template.dir flag to define another folder?

**Comment by xseth** [comment]
Thank you for your reply. 
Now I can run unifi-captive-portal. In the directory where there's the src 
`go run main.go `

**Comment by ipstatic** [comment]
That is because the `template.dir` flag is set to the current directory by default. If you want a different location, you can pass that flag (`go run main.go -template.dir=/some/other/directory/templates`) and it should start up without that directory present where `main.go` is located.
