### ISSUE TITLE
MissingRegion: could not find region configuration

### ISSUE THREAD

**Issue by xseth** [ipstatic/unifi-captive-portal#4]
Hi,

I have a new issueI I configured IAM role with dynamoDB and create credential profile. 
I have this error when I try to login guest user
`ERRO[0017] MissingRegion: could not find region configuration`
The guest user is successfuly authorized in unifi controller but I don't have email address in my table dynamodb.

**Comment by ipstatic** [comment]
Do you have a region set in your AWS config or as an ENV variable?

```
~/.aws/config
region = us-east-1
```
or
```
AWS_REGION=us-east-1
```

**Comment by xseth** [comment]
Thanks you for your reply I forgotten to create config file with region
Everything work great job 👍 💯

**Comment by ipstatic** [comment]
Thanks!
